# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orange.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# _runtime_version.ValidateProtobufRuntimeVersion(
#     _runtime_version.Domain.PUBLIC,
#     6,
#     31,
#     1,
#     '',
#     'orange.proto'
# )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corange.proto\x12\x06orange\"K\n\x10InferenceRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\"S\n\x11InferenceResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rprompt_tokens\x18\x02 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x03 \x01(\x05\"a\n\x0bProfileData\x12\x18\n\x10\x63omplexity_level\x18\x01 \x01(\t\x12\x0c\n\x04tone\x18\x02 \x01(\t\x12\x11\n\tinterests\x18\x03 \x03(\t\x12\x17\n\x0fraw_data_vector\x18\x04 \x01(\t\"3\n\x0fProfileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"E\n\rActionPayload\x12\x13\n\x0b\x61\x63tion_type\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\"e\n\x0e\x41\x63tionResponse\x12\x12\n\nauthorized\x18\x01 \x01(\x08\x12\x18\n\x10immune_triggered\x18\x02 \x01(\x08\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\"!\n\x11PythonCodeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"$\n\x12PythonCodeResponse\x12\x0e\n\x06stdout\x18\x01 \x01(\t\"\x1d\n\rDigestRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"2\n\x0e\x44igestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xea\x02\n\x0fOrangeInference\x12\x43\n\x0cRunDeduction\x12\x18.orange.InferenceRequest\x1a\x19.orange.InferenceResponse\x12\x41\n\x11UpdateUserProfile\x12\x13.orange.ProfileData\x1a\x17.orange.ProfileResponse\x12>\n\rRequestAction\x12\x15.orange.ActionPayload\x1a\x16.orange.ActionResponse\x12J\n\x11\x45xecutePythonCode\x12\x19.orange.PythonCodeRequest\x1a\x1a.orange.PythonCodeResponse\x12\x43\n\x12\x43ompileDailyDigest\x12\x15.orange.DigestRequest\x1a\x16.orange.DigestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=24
  _globals['_INFERENCEREQUEST']._serialized_end=99
  _globals['_INFERENCERESPONSE']._serialized_start=101
  _globals['_INFERENCERESPONSE']._serialized_end=184
  _globals['_PROFILEDATA']._serialized_start=186
  _globals['_PROFILEDATA']._serialized_end=283
  _globals['_PROFILERESPONSE']._serialized_start=285
  _globals['_PROFILERESPONSE']._serialized_end=336
  _globals['_ACTIONPAYLOAD']._serialized_start=338
  _globals['_ACTIONPAYLOAD']._serialized_end=407
  _globals['_ACTIONRESPONSE']._serialized_start=409
  _globals['_ACTIONRESPONSE']._serialized_end=510
  _globals['_PYTHONCODEREQUEST']._serialized_start=512
  _globals['_PYTHONCODEREQUEST']._serialized_end=545
  _globals['_PYTHONCODERESPONSE']._serialized_start=547
  _globals['_PYTHONCODERESPONSE']._serialized_end=583
  _globals['_DIGESTREQUEST']._serialized_start=585
  _globals['_DIGESTREQUEST']._serialized_end=614
  _globals['_DIGESTRESPONSE']._serialized_start=616
  _globals['_DIGESTRESPONSE']._serialized_end=666
  _globals['_ORANGEINFERENCE']._serialized_start=669
  _globals['_ORANGEINFERENCE']._serialized_end=1031
# @@protoc_insertion_point(module_scope)
