# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import orange_pb2 as orange__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orange_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrangeInferenceStub(object):
    """El servicio de Inferencia "Músculo Tonto", "Aduana" y "Bóveda" (Host Windows)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunDeduction = channel.unary_unary(
                '/orange.OrangeInference/RunDeduction',
                request_serializer=orange__pb2.InferenceRequest.SerializeToString,
                response_deserializer=orange__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.UpdateUserProfile = channel.unary_unary(
                '/orange.OrangeInference/UpdateUserProfile',
                request_serializer=orange__pb2.ProfileData.SerializeToString,
                response_deserializer=orange__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.RequestAction = channel.unary_unary(
                '/orange.OrangeInference/RequestAction',
                request_serializer=orange__pb2.ActionPayload.SerializeToString,
                response_deserializer=orange__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ExecutePythonCode = channel.unary_unary(
                '/orange.OrangeInference/ExecutePythonCode',
                request_serializer=orange__pb2.PythonCodeRequest.SerializeToString,
                response_deserializer=orange__pb2.PythonCodeResponse.FromString,
                _registered_method=True)
        self.CompileDailyDigest = channel.unary_unary(
                '/orange.OrangeInference/CompileDailyDigest',
                request_serializer=orange__pb2.DigestRequest.SerializeToString,
                response_deserializer=orange__pb2.DigestResponse.FromString,
                _registered_method=True)


class OrangeInferenceServicer(object):
    """El servicio de Inferencia "Músculo Tonto", "Aduana" y "Bóveda" (Host Windows)
    """

    def RunDeduction(self, request, context):
        """Recibe texto y parámetros, devuelve la respuesta pura generada por Qwen
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserProfile(self, request, context):
        """FASE 2.1: El Espejo (Perfilado Cognitivo)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAction(self, request, context):
        """FASE 3: La Aduana (Ejecución Autorizada y Sistema Inmune)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePythonCode(self, request, context):
        """PILAR 4: La Pecera Executor (Reverse RPC de Windows a Linux)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompileDailyDigest(self, request, context):
        """FASE 2.8: El Diario de Guerra (Compilación de Markdown)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrangeInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunDeduction': grpc.unary_unary_rpc_method_handler(
                    servicer.RunDeduction,
                    request_deserializer=orange__pb2.InferenceRequest.FromString,
                    response_serializer=orange__pb2.InferenceResponse.SerializeToString,
            ),
            'UpdateUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserProfile,
                    request_deserializer=orange__pb2.ProfileData.FromString,
                    response_serializer=orange__pb2.ProfileResponse.SerializeToString,
            ),
            'RequestAction': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAction,
                    request_deserializer=orange__pb2.ActionPayload.FromString,
                    response_serializer=orange__pb2.ActionResponse.SerializeToString,
            ),
            'ExecutePythonCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePythonCode,
                    request_deserializer=orange__pb2.PythonCodeRequest.FromString,
                    response_serializer=orange__pb2.PythonCodeResponse.SerializeToString,
            ),
            'CompileDailyDigest': grpc.unary_unary_rpc_method_handler(
                    servicer.CompileDailyDigest,
                    request_deserializer=orange__pb2.DigestRequest.FromString,
                    response_serializer=orange__pb2.DigestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orange.OrangeInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orange.OrangeInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrangeInference(object):
    """El servicio de Inferencia "Músculo Tonto", "Aduana" y "Bóveda" (Host Windows)
    """

    @staticmethod
    def RunDeduction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orange.OrangeInference/RunDeduction',
            orange__pb2.InferenceRequest.SerializeToString,
            orange__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orange.OrangeInference/UpdateUserProfile',
            orange__pb2.ProfileData.SerializeToString,
            orange__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orange.OrangeInference/RequestAction',
            orange__pb2.ActionPayload.SerializeToString,
            orange__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePythonCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orange.OrangeInference/ExecutePythonCode',
            orange__pb2.PythonCodeRequest.SerializeToString,
            orange__pb2.PythonCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompileDailyDigest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orange.OrangeInference/CompileDailyDigest',
            orange__pb2.DigestRequest.SerializeToString,
            orange__pb2.DigestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
